# Movies Recommendation system

In [1]:
# Importing required packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
# Importing given datasets

movies = pd.read_csv("C:/Users/navee/OneDrive/Desktop/GitHub/MLprojects/Movies_recommendation_system/Data/movies.csv")
credits = pd.read_csv("C:/Users/navee/OneDrive/Desktop/GitHub/MLprojects/Movies_recommendation_system/Data/credits.csv")

### Movies

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
movies.duplicated().sum()

# No duplicates found

0

In [5]:
# Info about movies table

movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

###### For creating movies recommendation system we need to find the similarity between the movies, so we required only those variables which can provide any information if that movie is similar with another ovie or not.

In [6]:
movies = movies[['genres', 'id', 'keywords', 'original_title', 'overview', 'spoken_languages', 'tagline', 'title']]

movies.head()

,genres,id,keywords,original_title,overview,spoken_languages,tagline,title
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,Avatar
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,Spectre
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,The Dark Knight Rises
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",John Carter

In [7]:
movies.isna().sum()

# We need null value tratment as there are some missings

genres                0
id                    0
keywords              0
original_title        0
overview              3
spoken_languages      0
tagline             844
title                 0
dtype: int64

In [8]:
# We need to drop the records where overview is itself missing as it contains lots of information 
# about the sismilarity of the movie which cannot be treated or replaced.

# Whereever "tagline" is missing we can replace null with blank ("") as it doesnot contain that much information
# and this will avoid the information loss also.


movies = movies.dropna(subset="overview")

movies = movies.fillna(value="")

movies.isna().sum()

genres              0
id                  0
keywords            0
original_title      0
overview            0
spoken_languages    0
tagline             0
title               0
dtype: int64

In [9]:
import json

In [10]:
# Extracting required information from variable "genres"

movies.genres.apply( lambda x: json.loads(x) )[1]

[{'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 28, 'name': 'Action'}]

In [11]:
# From variable gerne we need only "name"

movies.genres = movies.genres.apply( lambda x: [genres['name'] for genres in eval(x)])


movies.head()

,genres,id,keywords,original_title,overview,spoken_languages,tagline,title
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,Avatar
1,"[Adventure, Fantasy, Action]",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End
2,"[Action, Adventure, Crime]",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,Spectre
3,"[Action, Crime, Drama, Thriller]",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,The Dark Knight Rises
4,"[Action, Adventure, Science Fiction]",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",John Carter

In [12]:
# Likewise we have to do this for all columns


# Extracting required information from variable "genres"

json.loads(movies.loc[1, 'keywords'])

[{'id': 270, 'name': 'ocean'},
 {'id': 726, 'name': 'drug abuse'},
 {'id': 911, 'name': 'exotic island'},
 {'id': 1319, 'name': 'east india trading company'},
 {'id': 2038, 'name': "love of one's life"},
 {'id': 2052, 'name': 'traitor'},
 {'id': 2580, 'name': 'shipwreck'},
 {'id': 2660, 'name': 'strong woman'},
 {'id': 3799, 'name': 'ship'},
 {'id': 5740, 'name': 'alliance'},
 {'id': 5941, 'name': 'calypso'},
 {'id': 6155, 'name': 'afterlife'},
 {'id': 6211, 'name': 'fighter'},
 {'id': 12988, 'name': 'pirate'},
 {'id': 157186, 'name': 'swashbuckler'},
 {'id': 179430, 'name': 'aftercreditsstinger'}]

In [13]:
movies.keywords = movies.keywords.apply( lambda x: [keywords['name'] for keywords in eval(x)] )


movies.head()

,genres,id,keywords,original_title,overview,spoken_languages,tagline,title
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Enter the World of Pandora.,Avatar
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",A Plan No One Escapes,Spectre
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",The Legend Ends,The Dark Knight Rises
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[{""iso_639_1"": ""en"", ""name"": ""English""}]","Lost in our world, found in another.",John Carter

In [14]:
# Extracting required information from variable "spoken_languages"


movies.loc[1, 'spoken_languages']

'[{"iso_639_1": "en", "name": "English"}]'

In [15]:
movies.spoken_languages = movies.spoken_languages.apply( lambda x: 
                                                        [spoken_languages['name'] for spoken_languages in eval(x)] )


movies.head()

,genres,id,keywords,original_title,overview,spoken_languages,tagline,title
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[English, EspaÃ±ol]",Enter the World of Pandora.,Avatar
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",[English],"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[FranÃ§ais, English, EspaÃ±ol, Italiano, Deutsch]",A Plan No One Escapes,Spectre
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,[English],The Legend Ends,The Dark Knight Rises
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...",[English],"Lost in our world, found in another.",John Carter

### Credits

In [16]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
credits.info()

# No nulls available

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [18]:
credits.duplicated().sum()


# No duplicate found

0

In [19]:
# Extracting required information from variable "cast"


json.loads(credits.loc[1, 'cast'])

# Here, we need to extract both "character" and "name"

[{'cast_id': 4,
  'character': 'Captain Jack Sparrow',
  'credit_id': '52fe4232c3a36847f800b50d',
  'gender': 2,
  'id': 85,
  'name': 'Johnny Depp',
  'order': 0},
 {'cast_id': 5,
  'character': 'Will Turner',
  'credit_id': '52fe4232c3a36847f800b511',
  'gender': 2,
  'id': 114,
  'name': 'Orlando Bloom',
  'order': 1},
 {'cast_id': 6,
  'character': 'Elizabeth Swann',
  'credit_id': '52fe4232c3a36847f800b515',
  'gender': 1,
  'id': 116,
  'name': 'Keira Knightley',
  'order': 2},
 {'cast_id': 12,
  'character': 'William "Bootstrap Bill" Turner',
  'credit_id': '52fe4232c3a36847f800b52d',
  'gender': 2,
  'id': 1640,
  'name': 'Stellan SkarsgÃ¥rd',
  'order': 3},
 {'cast_id': 10,
  'character': 'Captain Sao Feng',
  'credit_id': '52fe4232c3a36847f800b525',
  'gender': 2,
  'id': 1619,
  'name': 'Chow Yun-fat',
  'order': 4},
 {'cast_id': 9,
  'character': 'Captain Davy Jones',
  'credit_id': '52fe4232c3a36847f800b521',
  'gender': 2,
  'id': 2440,
  'name': 'Bill Nighy',
  'order': 5},
 {'cast_id': 7,
  'character': 'Captain Hector Barbossa',
  'credit_id': '52fe4232c3a36847f800b519',
  'gender': 2,
  'id': 118,
  'name': 'Geoffrey Rush',
  'order': 6},
 {'cast_id': 14,
  'character': 'Admiral James Norrington',
  'credit_id': '52fe4232c3a36847f800b535',
  'gender': 2,
  'id': 1709,
  'name': 'Jack Davenport',
  'order': 7},
 {'cast_id': 13,
  'character': 'Joshamee Gibbs',
  'credit_id': '52fe4232c3a36847f800b531',
  'gender': 2,
  'id': 2449,
  'name': 'Kevin McNally',
  'order': 8},
 {'cast_id': 11,
  'character': 'Lord Cutler Beckett',
  'credit_id': '52fe4232c3a36847f800b529',
  'gender': 2,
  'id': 2441,
  'name': 'Tom Hollander',
  'order': 9},
 {'cast_id': 19,
  'character': 'Tia Dalma',
  'credit_id': '52fe4232c3a36847f800b549',
  'gender': 1,
  'id': 2038,
  'name': 'Naomie Harris',
  'order': 10},
 {'cast_id': 8,
  'character': 'Governor Weatherby Swann',
  'credit_id': '52fe4232c3a36847f800b51d',
  'gender': 2,
  'id': 378,
  'name': 'Jonathan Pryce',
  'order': 11},
 {'cast_id': 37,
  'character': 'Captain Teague Sparrow',
  'credit_id': '52fe4232c3a36847f800b5b3',
  'gender': 2,
  'id': 1430,
  'name': 'Keith Richards',
  'order': 12},
 {'cast_id': 16,
  'character': 'Pintel',
  'credit_id': '52fe4232c3a36847f800b53d',
  'gender': 2,
  'id': 1710,
  'name': 'Lee Arenberg',
  'order': 13},
 {'cast_id': 15,
  'character': 'Ragetti',
  'credit_id': '52fe4232c3a36847f800b539',
  'gender': 2,
  'id': 1711,
  'name': 'Mackenzie Crook',
  'order': 14},
 {'cast_id': 18,
  'character': 'Lieutenant Theodore Groves',
  'credit_id': '52fe4232c3a36847f800b545',
  'gender': 2,
  'id': 4031,
  'name': 'Greg Ellis',
  'order': 15},
 {'cast_id': 55,
  'character': 'Cotton',
  'credit_id': '57e28d2ec3a3681a01005b5c',
  'gender': 2,
  'id': 1715,
  'name': 'David Bailie',
  'order': 16},
 {'cast_id': 17,
  'character': 'Marty',
  'credit_id': '52fe4232c3a36847f800b541',
  'gender': 2,
  'id': 4030,
  'name': 'Martin Klebba',
  'order': 17},
 {'cast_id': 57,
  'character': 'Ian Mercer',
  'credit_id': '57e28d78c3a36808b900bf4f',
  'gender': 0,
  'id': 939,
  'name': 'David Schofield',
  'order': 18},
 {'cast_id': 62,
  'character': 'Scarlett',
  'credit_id': '57e28ec5c3a3681a50005855',
  'gender': 1,
  'id': 2450,
  'name': 'Lauren Maher',
  'order': 19},
 {'cast_id': 63,
  'character': 'Giselle',
  'credit_id': '57e28ed692514123f5005635',
  'gender': 1,
  'id': 2452,
  'name': 'Vanessa Branch',
  'order': 20},
 {'cast_id': 60,
  'character': 'Mullroy',
  'credit_id': '57e28db2c3a3681a01005bc7',
  'gender': 2,
  'id': 1714,
  'name': 'Angus Barnett',
  'order': 21},
 {'cast_id': 59,
  'character': 'Murtogg',
  'credit_id': '57e28da192514118f7006008',
  'gender': 0,
  'id': 1713,
  'name': 'Giles New',
  'order': 22},
 {'cast_id': 58,
  'character': 'Tai Huang',
  'credit_id': '57e28d8ec3a3681a01005bab',
  'gender': 2,
  'id': 22075,
  'name': 'Reggie Lee',
  'order': 23},
 {'cast_id': 64,
  'character': 'Henry Turner',
  'credit_id': '57e29119925141151100a6cc',
  'gender': 2,
  'id': 61259,
  'name': 'Dominic Scott Kay',
  'order': 24},
 {'cast_id': 39,
  'character': 'Mistress Ching',
  'credit_id': '52fe4232c3a36847f800b5bd',
  'gender': 1,
  'id': 33500,
  'name': 'Takayo Fischer',
  'order': 25},
 {'cast_id': 40,
  'character': 'Lieutenant Greitzer',
  'credit_id': '52fe4232c3a36847f800b5c1',
  'gender': 2,
  'id': 1224149,
  'name': 'David Meunier',
  'order': 26},
 {'cast_id': 49,
  'character': 'Hadras',
  'credit_id': '56d1871c92514174680010cf',
  'gender': 2,
  'id': 429401,
  'name': 'Ho-Kwan Tse',
  'order': 27},
 {'cast_id': 56,
  'character': 'Clacker',
  'credit_id': '57e28d4b92514125710055cb',
  'gender': 0,
  'id': 1123,
  'name': 'Andy Beckwith',
  'order': 28},
 {'cast_id': 51,
  'character': 'Penrod',
  'credit_id': '56ec8c14c3a3682260003c53',
  'gender': 2,
  'id': 1056117,
  'name': 'Peter Donald Badalamenti II',
  'order': 29},
 {'cast_id': 61,
  'character': "Cotton's Parrot (voice)",
  'credit_id': '57e28dcc9251412463005678',
  'gender': 2,
  'id': 21700,
  'name': 'Christopher S. Capp',
  'order': 30},
 {'cast_id': 65,
  'character': 'Captain Teague',
  'credit_id': '58bc2a37c3a368663003740b',
  'gender': 2,
  'id': 1430,
  'name': 'Keith Richards',
  'order': 31},
 {'cast_id': 66,
  'character': 'Captain Jocard',
  'credit_id': '58bc2a8e925141609e03a179',
  'gender': 2,
  'id': 2603,
  'name': 'Hakeem Kae-Kazim',
  'order': 32},
 {'cast_id': 67,
  'character': 'Captain Ammand',
  'credit_id': '58e2a21ac3a36872af00f9c2',
  'gender': 0,
  'id': 70577,
  'name': 'Ghassan Massoud',
  'order': 33}]

In [20]:
credits.cast = credits.cast.apply( lambda x: [cast['character'] for cast in 
                                              eval(x)]) + credits.cast.apply( lambda x: 
                                                                             [cast['name'] for cast in eval(x)])


credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[Jake Sully, Neytiri, Dr. Grace Augustine, Col...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Captain Jack Sparrow, Will Turner, Elizabeth ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[James Bond, Blofeld, Madeleine, M, Lucia, Q, ...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Bruce Wayne / Batman, Alfred Pennyworth, Jame...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[John Carter, Dejah Thoris, Sola, Tars Tarkas,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
# Extracting required information from variable "crew"


json.loads(credits.loc[1, 'crew'])


# Here, we need only name to be extracted

[{'credit_id': '52fe4232c3a36847f800b579',
  'department': 'Camera',
  'gender': 2,
  'id': 120,
  'job': 'Director of Photography',
  'name': 'Dariusz Wolski'},
 {'credit_id': '52fe4232c3a36847f800b4fd',
  'department': 'Directing',
  'gender': 2,
  'id': 1704,
  'job': 'Director',
  'name': 'Gore Verbinski'},
 {'credit_id': '52fe4232c3a36847f800b54f',
  'department': 'Production',
  'gender': 2,
  'id': 770,
  'job': 'Producer',
  'name': 'Jerry Bruckheimer'},
 {'credit_id': '52fe4232c3a36847f800b503',
  'department': 'Writing',
  'gender': 2,
  'id': 1705,
  'job': 'Screenplay',
  'name': 'Ted Elliott'},
 {'credit_id': '52fe4232c3a36847f800b509',
  'department': 'Writing',
  'gender': 2,
  'id': 1706,
  'job': 'Screenplay',
  'name': 'Terry Rossio'},
 {'credit_id': '52fe4232c3a36847f800b57f',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '52fe4232c3a36847f800b585',
  'department': 'Editing',
  'gender': 2,
  'id': 1722,
  'job': 'Editor',
  'name': 'Craig Wood'},
 {'credit_id': '52fe4232c3a36847f800b573',
  'department': 'Sound',
  'gender': 2,
  'id': 947,
  'job': 'Original Music Composer',
  'name': 'Hans Zimmer'},
 {'credit_id': '52fe4232c3a36847f800b555',
  'department': 'Production',
  'gender': 2,
  'id': 2444,
  'job': 'Executive Producer',
  'name': 'Mike Stenson'},
 {'credit_id': '52fe4232c3a36847f800b561',
  'department': 'Production',
  'gender': 2,
  'id': 2445,
  'job': 'Producer',
  'name': 'Eric McLeod'},
 {'credit_id': '52fe4232c3a36847f800b55b',
  'department': 'Production',
  'gender': 2,
  'id': 2446,
  'job': 'Producer',
  'name': 'Chad Oman'},
 {'credit_id': '52fe4232c3a36847f800b567',
  'department': 'Production',
  'gender': 0,
  'id': 2447,
  'job': 'Producer',
  'name': 'Peter Kohn'},
 {'credit_id': '52fe4232c3a36847f800b56d',
  'department': 'Production',
  'gender': 0,
  'id': 2448,
  'job': 'Producer',
  'name': 'Pat Sandston'},
 {'credit_id': '52fe4232c3a36847f800b58b',
  'department': 'Production',
  'gender': 1,
  'id': 2215,
  'job': 'Casting',
  'name': 'Denise Chamian'},
 {'credit_id': '52fe4232c3a36847f800b597',
  'department': 'Art',
  'gender': 2,
  'id': 1226,
  'job': 'Production Design',
  'name': 'Rick Heinrichs'},
 {'credit_id': '52fe4232c3a36847f800b59d',
  'department': 'Art',
  'gender': 2,
  'id': 553,
  'job': 'Art Direction',
  'name': 'John Dexter'},
 {'credit_id': '52fe4232c3a36847f800b591',
  'department': 'Production',
  'gender': 1,
  'id': 3311,
  'job': 'Casting',
  'name': 'Priscilla John'},
 {'credit_id': '52fe4232c3a36847f800b5a3',
  'department': 'Art',
  'gender': 1,
  'id': 4032,
  'job': 'Set Decoration',
  'name': 'Cheryl Carasik'},
 {'credit_id': '52fe4232c3a36847f800b5a9',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 4033,
  'job': 'Costume Design',
  'name': 'Liz Dann'},
 {'credit_id': '52fe4232c3a36847f800b5af',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 4034,
  'job': 'Costume Design',
  'name': 'Penny Rose'},
 {'credit_id': '56427ce8c3a3686a53000d8b',
  'department': 'Sound',
  'gender': 2,
  'id': 5132,
  'job': 'Music Supervisor',
  'name': 'Bob Badami'},
 {'credit_id': '55993c15c3a36855db002f33',
  'department': 'Art',
  'gender': 2,
  'id': 146439,
  'job': 'Conceptual Design',
  'name': 'James Ward Byrkit'},
 {'credit_id': '52fe4232c3a36847f800b5b9',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 406204,
  'job': 'Makeup Department Head',
  'name': 'Ve Neill'},
 {'credit_id': '56e47f7892514132690017bd',
  'department': 'Crew',
  'gender': 2,
  'id': 1259516,
  'job': 'Stunts',
  'name': 'John Dixon'},
 {'credit_id': '5740be639251416597000849',
  'department': 'Crew',
  'gender': 0,
  'id': 1336716,
  'job': 'CGI Supervisor',
  'name': 'Dottie Starling'},
 {'credit_id': '56427c639251412fc8000dc1',
  'department': 'Directing',
  'gender': 1,
  'id': 1344278,
  'job': 'Script Supervisor',
  'name': 'Pamela Alch'},
 {'credit_id': '57083101c3a3681d320004e6',
  'department': 'Crew',
  'gender': 0,
  'id': 1368867,
  'job': 'Special Effects Coordinator',
  'name': 'Allen Hall'},
 {'credit_id': '56427d5ec3a3686a62000d4a',
  'department': 'Sound',
  'gender': 0,
  'id': 1368884,
  'job': 'Music Editor',
  'name': 'Melissa Muik'},
 {'credit_id': '56427c7b9251412fd4000e07',
  'department': 'Directing',
  'gender': 1,
  'id': 1395290,
  'job': 'Script Supervisor',
  'name': 'Sharron Reynolds'},
 {'credit_id': '56427d2bc3a3686a53000d9b',
  'department': 'Sound',
  'gender': 0,
  'id': 1399327,
  'job': 'Music Editor',
  'name': 'Barbara McDermott'},
 {'credit_id': '56427cb4c3a3686a53000d87',
  'department': 'Directing',
  'gender': 1,
  'id': 1400738,
  'job': 'Script Supervisor',
  'name': 'Karen Golden'},
 {'credit_id': '56427d169251412fd4000e23',
  'department': 'Sound',
  'gender': 0,
  'id': 1534197,
  'job': 'Music Editor',
  'name': 'Katie Greathouse'}]

In [22]:
credits.crew = credits.crew.apply( lambda x: [crew['name'] for crew in eval(x)] )


credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[Jake Sully, Neytiri, Dr. Grace Augustine, Col...","[Stephen E. Rivkin, Rick Carter, Christopher B..."
1,285,Pirates of the Caribbean: At World's End,"[Captain Jack Sparrow, Will Turner, Elizabeth ...","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe..."
2,206647,Spectre,"[James Bond, Blofeld, Madeleine, M, Lucia, Q, ...","[Thomas Newman, Sam Mendes, Anna Pinnock, John..."
3,49026,The Dark Knight Rises,"[Bruce Wayne / Batman, Alfred Pennyworth, Jame...","[Hans Zimmer, Charles Roven, Christopher Nolan..."
4,49529,John Carter,"[John Carter, Dejah Thoris, Sola, Tars Tarkas,...","[Andrew Stanton, Andrew Stanton, John Lasseter..."

In [23]:
credits

,movie_id,title,cast,crew
0,19995,Avatar,"[Jake Sully, Neytiri, Dr. Grace Augustine, Col...","[Stephen E. Rivkin, Rick Carter, Christopher B..."
1,285,Pirates of the Caribbean: At World's End,"[Captain Jack Sparrow, Will Turner, Elizabeth ...","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe..."
2,206647,Spectre,"[James Bond, Blofeld, Madeleine, M, Lucia, Q, ...","[Thomas Newman, Sam Mendes, Anna Pinnock, John..."
3,49026,The Dark Knight Rises,"[Bruce Wayne / Batman, Alfred Pennyworth, Jame...","[Hans Zimmer, Charles Roven, Christopher Nolan..."
4,49529,John Carter,"[John Carter, Dejah Thoris, Sola, Tars Tarkas,...","[Andrew Stanton, Andrew Stanton, John Lasseter..."
...,...,...,...,...
4798,9367,El Mariachi,"[El Mariachi, BigotÃ³n, Mauricio (Moco), Azul, ...","[Robert Rodriguez, Robert Rodriguez, Robert Ro..."
4799,72766,Newlyweds,"[Buzzy, Linda, Marsha, Katie, Vanessa, Edward ...","[Edward Burns, Edward Burns, Edward Burns, Wil..."
4800,231617,"Signed, Sealed, Delivered","[Oliver Oâ€™Toole, Shane McInerney, Rita Haywith...","[Carla Hetland, Harvey Kahn, Adam Sliwinski, M..."
4801,126186,Shanghai Calling,"[Sam, Amanda, Donald, Marcus Groff, , Daniel H...","[Daniel Hsia, Daniel Hsia]"
4802,25975,My Date with Drew,"[Herself, Himself, Himself, Himself, Himself, ...","[Clark Peterson, Andrew Reimer, Brian Herzling..."

In [24]:
# Mergeing both the datasets


df = pd.merge(left=movies, right=credits, left_on=['id', 'title'], right_on=['movie_id', 'title'], how='inner')

In [25]:
df

,genres,id,keywords,original_title,overview,spoken_languages,tagline,title,movie_id,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[English, EspaÃ±ol]",Enter the World of Pandora.,Avatar,19995,"[Jake Sully, Neytiri, Dr. Grace Augustine, Col...","[Stephen E. Rivkin, Rick Carter, Christopher B..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",[English],"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,285,"[Captain Jack Sparrow, Will Turner, Elizabeth ...","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[FranÃ§ais, English, EspaÃ±ol, Italiano, Deutsch]",A Plan No One Escapes,Spectre,206647,"[James Bond, Blofeld, Madeleine, M, Lucia, Q, ...","[Thomas Newman, Sam Mendes, Anna Pinnock, John..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,[English],The Legend Ends,The Dark Knight Rises,49026,"[Bruce Wayne / Batman, Alfred Pennyworth, Jame...","[Hans Zimmer, Charles Roven, Christopher Nolan..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...",[English],"Lost in our world, found in another.",John Carter,49529,"[John Carter, Dejah Thoris, Sola, Tars Tarkas,...","[Andrew Stanton, Andrew Stanton, John Lasseter..."
...,...,...,...,...,...,...,...,...,...,...,...
4794,"[Action, Crime, Thriller]",9367,"[united statesâ€“mexico barrier, legs, arms, pap...",El Mariachi,El Mariachi just wants to play his guitar and ...,[EspaÃ±ol],"He didn't come looking for trouble, but troubl...",El Mariachi,9367,"[El Mariachi, BigotÃ³n, Mauricio (Moco), Azul, ...","[Robert Rodriguez, Robert Rodriguez, Robert Ro..."
4795,"[Comedy, Romance]",72766,[],Newlyweds,A newlywed couple's honeymoon is upended by th...,[],A newlywed couple's honeymoon is upended by th...,Newlyweds,72766,"[Buzzy, Linda, Marsha, Katie, Vanessa, Edward ...","[Edward Burns, Edward Burns, Edward Burns, Wil..."
4796,"[Comedy, Drama, Romance, TV Movie]",231617,"[date, love at first sight, narration, investi...","Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",[English],,"Signed, Sealed, Delivered",231617,"[Oliver Oâ€™Toole, Shane McInerney, Rita Haywith...","[Carla Hetland, Harvey Kahn, Adam Sliwinski, M..."
4797,[],126186,[],Shanghai Calling,When ambitious New York attorney Sam is sent t...,[English],A New Yorker in Shanghai,Shanghai Calling,126186,"[Sam, Amanda, Donald, Marcus Groff, , Daniel H...","[Daniel Hsia, Daniel Hsia]"
4798,[Documentary],25975,"[obsession, camcorder, crush, dream girl]",My Date with Drew,Ever since the second grade when he first saw ...,[English],,My Date with Drew,25975,"[Herself, Himself, Himself, Himself, Himself, ...","[Clark Peterson, Andrew Reimer, Brian Herzling..."

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4799 entries, 0 to 4798
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   genres            4799 non-null   object
 1   id                4799 non-null   int64
 2   keywords          4799 non-null   object
 3   original_title    4799 non-null   object
 4   overview          4799 non-null   object
 5   spoken_languages  4799 non-null   object
 6   tagline           4799 non-null   object
 7   title             4799 non-null   object
 8   movie_id          4799 non-null   int64
 9   cast              4799 non-null   object
 10  crew              4799 non-null   object
dtypes: int64(2), object(9)
memory usage: 412.5+ KB

In [27]:
import re

In [28]:
# Tokenization for variable "overview"

df['overview'] = df['overview'].apply(lambda x: re.split(r'[ :`~#!@$%\^&*()\[\]{}\-_+=;\"<,.>/?|]', x))

df['tagline'] = df['tagline'].apply(lambda x: re.split(r'[ :`~#!@$%\^&*()\[\]{}\-_+=;\"<,.>/?|]', x))

In [29]:
import string
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
from wordcloud import STOPWORDS

stp_words = list(set(list(ENGLISH_STOP_WORDS) + list(STOPWORDS)))

In [30]:
# Removing stopwords, single charaters and panctuations

df['overview'] = df.overview.apply( lambda x: [w for w in x if 
                                               len(w) > 1 and 
                                               w not in stp_words and 
                                               w not in string.punctuation] )


df['tagline'] = df.tagline.apply( lambda x: [w for w in x if 
                                               len(w) > 1 and 
                                               w not in stp_words and 
                                               w not in string.punctuation] )

In [31]:
df = df[['movie_id', 'title', 'overview', 'tagline', 'genres', 'keywords', 'spoken_languages', 'cast', 'crew']]

In [32]:
df['merged_col_1'] = df.overview + df.tagline + df.keywords


df = df.drop(columns=['overview' , 'tagline' , 'keywords'])


df.head()

C:\Users\navee\AppData\Local\Temp\ipykernel_3296\4061799950.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['merged_col_1'] = df.overview + df.tagline + df.keywords

,movie_id,title,genres,spoken_languages,cast,crew,merged_col_1
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[English, EspaÃ±ol]","[Jake Sully, Neytiri, Dr. Grace Augustine, Col...","[Stephen E. Rivkin, Rick Carter, Christopher B...","[In, 22nd, century, paraplegic, Marine, dispat..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",[English],"[Captain Jack Sparrow, Will Turner, Elizabeth ...","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...","[Captain, Barbossa, long, believed, dead, come..."
2,206647,Spectre,"[Action, Adventure, Crime]","[FranÃ§ais, English, EspaÃ±ol, Italiano, Deutsch]","[James Bond, Blofeld, Madeleine, M, Lucia, Q, ...","[Thomas Newman, Sam Mendes, Anna Pinnock, John...","[cryptic, message, Bondâ€™s, past, sends, trail,..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",[English],"[Bruce Wayne / Batman, Alfred Pennyworth, Jame...","[Hans Zimmer, Charles Roven, Christopher Nolan...","[Following, death, District, Attorney, Harvey,..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]",[English],"[John Carter, Dejah Thoris, Sola, Tars Tarkas,...","[Andrew Stanton, Andrew Stanton, John Lasseter...","[John, Carter, war, weary, military, captain, ..."

In [33]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
from textblob import TextBlob

In [34]:
df.merged_col_1 = df.merged_col_1.apply( lambda x: " ".join(x))


df.merged_col_1 = df.merged_col_1.apply( lambda x: WordNetLemmatizer().lemmatize(x) )


df.head()

,movie_id,title,genres,spoken_languages,cast,crew,merged_col_1
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[English, EspaÃ±ol]","[Jake Sully, Neytiri, Dr. Grace Augustine, Col...","[Stephen E. Rivkin, Rick Carter, Christopher B...",In 22nd century paraplegic Marine dispatched m...
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",[English],"[Captain Jack Sparrow, Will Turner, Elizabeth ...","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...",Captain Barbossa long believed dead come life ...
2,206647,Spectre,"[Action, Adventure, Crime]","[FranÃ§ais, English, EspaÃ±ol, Italiano, Deutsch]","[James Bond, Blofeld, Madeleine, M, Lucia, Q, ...","[Thomas Newman, Sam Mendes, Anna Pinnock, John...",cryptic message Bondâ€™s past sends trail uncove...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",[English],"[Bruce Wayne / Batman, Alfred Pennyworth, Jame...","[Hans Zimmer, Charles Roven, Christopher Nolan...",Following death District Attorney Harvey Dent ...
4,49529,John Carter,"[Action, Adventure, Science Fiction]",[English],"[John Carter, Dejah Thoris, Sola, Tars Tarkas,...","[Andrew Stanton, Andrew Stanton, John Lasseter...",John Carter war weary military captain inexpli...

In [35]:
df['merged_col_2'] = df.genres + df.spoken_languages + df.cast + df.crew

df.merged_col_2 = df.merged_col_2.apply( lambda x: " ".join(x))

df.head()

,movie_id,title,genres,spoken_languages,cast,crew,merged_col_1,merged_col_2
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[English, EspaÃ±ol]","[Jake Sully, Neytiri, Dr. Grace Augustine, Col...","[Stephen E. Rivkin, Rick Carter, Christopher B...",In 22nd century paraplegic Marine dispatched m...,Action Adventure Fantasy Science Fiction Engli...
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",[English],"[Captain Jack Sparrow, Will Turner, Elizabeth ...","[Dariusz Wolski, Gore Verbinski, Jerry Bruckhe...",Captain Barbossa long believed dead come life ...,Adventure Fantasy Action English Captain Jack ...
2,206647,Spectre,"[Action, Adventure, Crime]","[FranÃ§ais, English, EspaÃ±ol, Italiano, Deutsch]","[James Bond, Blofeld, Madeleine, M, Lucia, Q, ...","[Thomas Newman, Sam Mendes, Anna Pinnock, John...",cryptic message Bondâ€™s past sends trail uncove...,Action Adventure Crime FranÃ§ais English EspaÃ±o...
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",[English],"[Bruce Wayne / Batman, Alfred Pennyworth, Jame...","[Hans Zimmer, Charles Roven, Christopher Nolan...",Following death District Attorney Harvey Dent ...,Action Crime Drama Thriller English Bruce Wayn...
4,49529,John Carter,"[Action, Adventure, Science Fiction]",[English],"[John Carter, Dejah Thoris, Sola, Tars Tarkas,...","[Andrew Stanton, Andrew Stanton, John Lasseter...",John Carter war weary military captain inexpli...,Action Adventure Science Fiction English John ...

In [36]:
df = df.drop(columns=['genres','spoken_languages','cast','crew'])

df.head()

,movie_id,title,merged_col_1,merged_col_2
0,19995,Avatar,In 22nd century paraplegic Marine dispatched m...,Action Adventure Fantasy Science Fiction Engli...
1,285,Pirates of the Caribbean: At World's End,Captain Barbossa long believed dead come life ...,Adventure Fantasy Action English Captain Jack ...
2,206647,Spectre,cryptic message Bondâ€™s past sends trail uncove...,Action Adventure Crime FranÃ§ais English EspaÃ±o...
3,49026,The Dark Knight Rises,Following death District Attorney Harvey Dent ...,Action Crime Drama Thriller English Bruce Wayn...
4,49529,John Carter,John Carter war weary military captain inexpli...,Action Adventure Science Fiction English John ...

In [37]:
df['merged_col'] = df.merged_col_1 + ' ' + df.merged_col_2

df = df.drop(columns=['merged_col_1', 'merged_col_2'])

df.head()

,movie_id,title,merged_col
0,19995,Avatar,In 22nd century paraplegic Marine dispatched m...
1,285,Pirates of the Caribbean: At World's End,Captain Barbossa long believed dead come life ...
2,206647,Spectre,cryptic message Bondâ€™s past sends trail uncove...
3,49026,The Dark Knight Rises,Following death District Attorney Harvey Dent ...
4,49529,John Carter,John Carter war weary military captain inexpli...

# Vectorization

In [38]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [39]:
cv = CountVectorizer(token_pattern=r'\b[a-zA-Z]+\b', max_features=10000)

In [40]:
X = cv.fit_transform(df.merged_col)

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

X = cosine_similarity(X)

In [42]:
X

array([[1.        , 0.13642168, 0.24502305, ..., 0.06545425, 0.02393956,
        0.03175502],
       [0.13642168, 1.        , 0.17161256, ..., 0.0630706 , 0.04335883,
        0.0478478 ],
       [0.24502305, 0.17161256, 1.        , ..., 0.08930329, 0.0756448 ,
        0.0808368 ],
       ...,
       [0.06545425, 0.0630706 , 0.08930329, ..., 1.        , 0.04714045,
        0.04965635],
       [0.02393956, 0.04335883, 0.0756448 , ..., 0.04714045, 1.        ,
        0.04876714],
       [0.03175502, 0.0478478 , 0.0808368 , ..., 0.04965635, 0.04876714,
        1.        ]])

In [51]:
def recommend_movie(movie):
    movie_index = df[df['title'] == movie].index[0]
    distances = X[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movie_list:
        print(df.iloc[i[0]].title)

In [55]:
recommend_movie('Liar Liar')

Bruce Almighty
The Relic
End of Days
Jurassic World
Deep Impact